# Generated by Django 4.2.4 on 2023-11-10 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colección',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_de_publicacion', models.DateField(blank=True, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('resumen', models.CharField(blank=True, max_length=1500, null=True)),
                ('genero', models.CharField(choices=[('Ciencia Ficción', 'Ciencia Ficción'), ('Romance', 'Romance'), ('Misterio', 'Misterio'), ('Fantasía', 'Fantasía'), ('Aventura', 'Aventura'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Biografía', 'Biografía'), ('Autoayuda', 'Autoayuda'), ('Histórico', 'Histórico'), ('Infantil', 'Infantil')], max_length=200)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('idioma', models.CharField(max_length=100)),
                ('numero_de_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_de_entrada', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
