# Generated by Django 4.2.4 on 2023-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colección', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colección',
            name='idioma',
            field=models.CharField(choices=[('Español', 'Español'), ('Ingles', 'Ingles'), ('Italiano', 'Misterio'), ('Braille', 'Braille'), ('Latín', 'Latín'), ('Alemán', 'Alemán'), ('Francés', 'Francés'), ('Portugués', 'Portugués'), ('Chino', 'Chino'), ('Japonés', 'Japonés'), ('Ruso', 'Ruso'), ('Árabe', 'Árabe')], max_length=100),
        ),
    ]
