# Generated by Django 3.1.3 on 2023-11-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colección', '0002_alter_colección_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colección',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
