# Generated by Django 4.2.7 on 2023-11-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colección', '0003_auto_20231113_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colección',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='colección',
            name='resumen',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
