# Generated by Django 4.2.4 on 2023-11-10 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colección', '0002_alter_colección_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_de_devolucion', models.DateField()),
                ('libros', models.ManyToManyField(related_name='prestamos', to='colección.colección')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(max_length=100)),
                ('fecha_de_registro', models.DateField(default=django.utils.timezone.now)),
                ('adeuda', models.BooleanField(default=False)),
                ('historial_de_prestamos', models.ManyToManyField(blank=True, to='usuarios.prestamos')),
            ],
        ),
        migrations.AddField(
            model_name='prestamos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
