# Generated by Django 4.2.7 on 2023-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_prestamos_id_alter_usuarios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
